version: '3.8'
services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - 8080:80
    stop_grace_period: 60s
    volumes:
      # change to your own hdd route
      - /mnt/share/apps/overleaf/data:/var/lib/overleaf/data
      # change to your own ssd route
      - /mnt/app/overleaf/compiles:/var/lib/overleaf/data/compiles
      - /mnt/app/overleaf/output:/var/lib/overleaf/data/output
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo:27017/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"
      SANDBOXED_COMPILES: "true"
      SANDBOXED_COMPILES_HOST_DIR_COMPILES: "/var/lib/overleaf/data/compiles"
      SANDBOXED_COMPILES_HOST_DIR_OUTPUT: "/var/lib/overleaf/data/output"
      DOCKER_RUNNER: "true"
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: "true"
  mongo:
    restart: always
    image: mongo:8.0
    container_name: mongo
    volumes:
      # change to your own ssd route
      - /mnt/share/apps/overleaf/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  redis:
    restart: always
    image: redis:6.2
    container_name: redis
    volumes:
      # change to your own ssd route
      - /mnt/share/apps/overleaf/redis:/data
